### ISSUE TITLE
Is possible to use this driver on the ESP32 too?

### ISSUE THREAD

**Issue by beyonlo** [SteveSEK/Raspberry-Pi-Pico-MicroPython-Ethernet#1]
Hi, great work :)

I would like to use an ethernet on the ESP32-S3 with the WIZnet ethernet chip, with SSL, like as you did with RPICO. Is possible to use this driver to works in the same way with ESP32 family (ESP32/S2/S3/C3) that use the same ESP-IDF?

Thank you so much.

**Comment by SteveSEK** [comment]
Sure.
It may require some modifications, but I think it's possible.

**Comment by beyonlo** [comment]
> Sure. It may require some modifications, but I think it's possible.

Hello!

Do you have interest to do that? If not, could please tell me what exactly I need to change? Let me explain: I'm a newbie, I never build a MicroPython, I just flash my ESP32  and RPICO from a ready image do use it. But if you point me some docs that I need to follow, I can to try.

Thank you in advance!

**Comment by SteveSEK** [comment]
I marked the part I modified in official micropython repository as below.
///2xxxxx some comments 

If you search by word "///21" or "///22", you can find the edited part in the original repository source files.

By the way, this is just a my personal project using the WIZNet chip's MacRaw-mode. How about referring to WIZnet's official project?

**Comment by beyonlo** [comment]
Hello!

> By the way, this is just a my personal project using the WIZNet chip's MacRaw-mode. How about referring to WIZnet's official project?

I already tried that, but no answer. I creatd an issue in the Winznet Github, in the specific project about Wiznet MicroPython support: https://github.com/Wiznet/RP2040-HAT-MicroPython/issues/10  I Do not know why they no answer and/or did not that support, because they will sell more chips.

Thank you!
